# Generated by Django 4.0.5 on 2022-06-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='commands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=20)),
                ('repetition', models.IntegerField()),
                ('sleep_dur', models.IntegerField()),
            ],
        ),
    ]
